controllers:
    resource: ../src/Controller/
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index
    
task_index:
    path: /tasks
    controller: App\Controller\TaskController::index
    methods: [GET, POST]
    # schemes: [HTTPS]
    # host: {nome_usuario}.'tarefas.test'

task_show:
    path: /tasks/show/{id?10}
    controller: App\Controller\TaskController::show
    requirements:
        id: '\d+'
    methods: [GET]
    condition: "context.getMethod() in ['GET'] and request.headers.get('User-Agent') matches '/Chrome/i'"
    # defaults:
    #     id: 0

task_new: 
    path: /tasks/new
    controller: App\Controller\TaskController::new
    methods: [GET, POST]

task_edit:
    path: /tasks/{id}/edit
    controller: App\Controller\TaskController::edit
    methods: [GET, POST]

task_delete:
    path: /tasks/{id}
    controller: App\Controller\TaskController::delete
    methods: [DELETE]